---
title: "Sähkö"
author: "TeroJii"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggthemes)

theme_set(theme_base())
```


# Alkuvuoden lämpötila vaihtelut

Simuloidaan alkuvuoden keskilämpötiloja historiallisten havaintojen perusteella.

```{r}

N <- 50

# Keskiarvot Kaisaniemen havaintoaseman keskilt. 1991-2020
tammikuu <- rnorm(N, mean = -3.1, sd = 3)
helmikuu <- rnorm(N, mean = -3.8, sd = 3)
maaliskuu <- rnorm(N, mean = -0.7, sd = 3)

data.frame(tammikuu, helmikuu, maaliskuu, x = 1:50) %>%
  pivot_longer(cols = -x, names_to = "kuukausi", values_to = "temp") %>% 
  ggplot(aes(y = temp, x = x)) +
  geom_line() +
  facet_grid(. ~kuukausi)
```


## Lämpötila vs. kulutus

```{r}

temps <- c(-1.9, -1.6, 1, 3.9, -5.3, 2)
kwhs <- c(1807, 1548, 1429, 1012, 2239, 1407)

data.frame(temps, kwhs) %>% 
  ggplot(aes(y = temps, x = kwhs)) +
  geom_point() + 
  geom_hline(yintercept = 0, color = "red", lty = 2) +
  geom_smooth(method = "lm") +
  labs(y = "Temperature", x = "Consumption (kwh)")
```

